steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/gold-project-465505/gold-docker-repo/gold-calculator-app:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/gold-project-465505/gold-docker-repo/gold-calculator-app:$SHORT_SHA' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'gold-calculator-service',
        '--image',
        'us-central1-docker.pkg.dev/gold-project-465505/gold-docker-repo/gold-calculator-app:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

